name: Mirror to GitLab

on:
  push:
    branches:
      - '**' 

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git credentials for HTTPS
        run: |
          git config --global credential.helper store
          echo "https://i540273:3yoYMzMAHANX3yzEVm_i@git.fhict.nl/I540273/eventify-mirror.git" > ~/.git-credentials

      - name: Push to GitLab
        run: |
          git remote add gitlab https://git.fhict.nl/I540273/eventify-mirror.git
          git push gitlab --mirror  

      - name: Remove credentials
        run: |
          rm ~/.git-credentials  
